name: biomni
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - blast
  - samtools
  - bowtie2
  - bwa
  - bedtools
  - fastqc
  - trimmomatic
  - mafft
  - gseapy
  - mageck
  - plannotate
  - pyranges
  - biopython
  - pybedtools
  - python-igraph
  - pysam
  - llvmlite
  - pyfaidx
  - scanpy
  - igraph
  - numba
  - leidenalg
  - r-essentials
  - r-base[version='>=4.4']
prefix: /users/mac/miniconda3/envs/biomni_e1
